import customizerActions from "./customizerActions";
import customizerMutations from "./customizerMutations";

export default {
  namespaced: true,
  state: {
    activeTab: "customizer",
    customizerTools: [
      {
        name: "Button",
        type: "button",
        icon: "plus-square",
        defaultProperties: {
          fullBorderWidth: true,
          align: "center",
          paddingLeft: 5,
          paddingRight: 5,
          paddingTop: 5,
          paddingBottom: 5,
          borderTopWidth: 1,
          borderBottomWidth: 1,
          borderLeftWidth: 1,
          borderRightWidth: 1,
          borderWidth: 1,
          borderStyle: "solid",
          borderColor: "#40e0d0",
          textValue: "Button",
          borderRadius: 5,
          width: 30,
          color: "#ffffff",
          backgroundColor: "#40e0d0",
          rowBackgroundColor: "#ffffff",
          fontSize: 14,
        },
        validSettings: [
          "AlignSetting",
          "BorderSetting",
          "ButtonTextSetting",
          "FontSizeSetting",
          "WidthSetting",
          "HeightSetting",
        ],
      },
      {
        name: "Input",
        type: "input",
        icon: "font-colors",
        defaultProperties: {
          align: "center",
          paddingLeft: 5,
          paddingRight: 5,
          paddingTop: 5,
          paddingBottom: 5,
          borderWidth: 1,
          borderStyle: "solid",
          borderColor: "#40e0d0",
          placeholder: "Enter input",
          borderRadius: 5,
          width: 30,
          rowBackgroundColor: "#ffffff",
        },
        validSettings: [
          "AlignSetting",
          "BorderSetting",
          "ButtonTextSetting",
          "FontSizeSetting",
        ],
      },
      {
        name: "Text Area",
        type: "textarea",
        icon: "bold",
        defaultProperties: {
          align: "center",
          paddingLeft: 5,
          paddingRight: 5,
          paddingTop: 5,
          paddingBottom: 5,
          borderWidth: 1,
          borderStyle: "solid",
          borderColor: "#40e0d0",
          placeholder: "Enter input",
          borderRadius: 5,
          width: 30,
          rowBackgroundColor: "#ffffff",
        },
        validSettings: [
          "AlignSetting",
          "BorderSetting",
          "ButtonTextSetting",
          "FontSizeSetting",
        ],
      },
      {
        name: "Check Box",
        type: "checkbox",
        icon: "check",
        defaultProperties: {
          align: "center",
          rowBackgroundColor: "#ffffff",
          checkboxName: "",
          checkboxValue: "",
          checkboxText: "Check box",
        },
        validSettings: [
          "AlignSetting",
          "BorderSetting",
          "ButtonTextSetting",
          "FontSizeSetting",
        ],
      },
      {
        name: "Radio Button",
        type: "radio",
        icon: "plus-circle",
        defaultProperties: {
          align: "center",
          rowBackgroundColor: "#ffffff",
          radioName: "",
          radioValue: "",
          radioText: "Radio button",
        },
        validSettings: [
          "AlignSetting",
          "BorderSetting",
          "ButtonTextSetting",
          "FontSizeSetting",
        ],
      },
    ],
    currentRow: {
      rowId: "xy12345678",
      validSettings: [
        "AlignSetting",
        "BorderSetting",
        "ButtonTextSetting",
        "FontSizeSetting",
      ],
    },
  },
  actions: customizerActions,
  mutations: customizerMutations,
};
